//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIIDFinalEntities : DbContext
    {
        public BIIDFinalEntities()
            : base("name=BIIDFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AgriculturalCulturalOperation> AgriculturalCulturalOperations { get; set; }
        public DbSet<BirdAndLivestockCulturalOperation> BirdAndLivestockCulturalOperations { get; set; }
        public DbSet<BirdAndLiveStockVaccination> BirdAndLiveStockVaccinations { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<CustmerProfile> CustmerProfiles { get; set; }
        public DbSet<CustomerDistrict> CustomerDistricts { get; set; }
        public DbSet<CustomerSearch> CustomerSearches { get; set; }
        public DbSet<CustomerUpozilla> CustomerUpozillas { get; set; }
        public DbSet<DetailsSupplierInfo> DetailsSupplierInfoes { get; set; }
        public DbSet<DiseaseAndPestManagement> DiseaseAndPestManagements { get; set; }
        public DbSet<EquipmentAndTechnology> EquipmentAndTechnologies { get; set; }
        public DbSet<Fertilizer> Fertilizers { get; set; }
        public DbSet<FishCulturalOperation> FishCulturalOperations { get; set; }
        public DbSet<HarvestingManagement> HarvestingManagements { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<LivestockFeedPreservation> LivestockFeedPreservations { get; set; }
        public DbSet<NutritionalStatu> NutritionalStatus { get; set; }
        public DbSet<OrganizationSectorRelation> OrganizationSectorRelations { get; set; }
        public DbSet<Planting> Plantings { get; set; }
        public DbSet<PreparationOfFeed> PreparationOfFeeds { get; set; }
        public DbSet<Sector> Sectors { get; set; }
        public DbSet<SeedProduction> SeedProductions { get; set; }
        public DbSet<SupplierAddress> SupplierAddresses { get; set; }
        public DbSet<SupplierCategory> SupplierCategories { get; set; }
        public DbSet<SupplierDistrict> SupplierDistricts { get; set; }
        public DbSet<SupplierUpozilla> SupplierUpozillas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tip> Tips { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<Variety> Varieties { get; set; }
    }
}
