//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirdAndLivestockCulturalOperation
    {
        public int Id { get; set; }
        public string StageName { get; set; }
        public string HouseManagement { get; set; }
        public string LightManagement { get; set; }
        public string HeatManagement { get; set; }
        public string FoodManagement { get; set; }
        public string FarmManagement { get; set; }
        public string Precaution { get; set; }
        public string Remarks { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
