//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirdAndLiveStockVaccination
    {
        public int Id { get; set; }
        public string Age { get; set; }
        public string NameOfDisease { get; set; }
        public string NameOfVaccine { get; set; }
        public string ApplicationProcedure { get; set; }
        public string Precaution { get; set; }
        public string Remarks { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
