//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDistrict
    {
        public CustomerDistrict()
        {
            this.CustomerUpozillas = new HashSet<CustomerUpozilla>();
            this.SupplierAddresses = new HashSet<SupplierAddress>();
            this.SupplierDistricts = new HashSet<SupplierDistrict>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CustomerUpozilla> CustomerUpozillas { get; set; }
        public virtual ICollection<SupplierAddress> SupplierAddresses { get; set; }
        public virtual ICollection<SupplierDistrict> SupplierDistricts { get; set; }
    }
}
