//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustmerProfile
    {
        public CustmerProfile()
        {
            this.CustomerSearches = new HashSet<CustomerSearch>();
        }
    
        public int Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string District { get; set; }
        public string Upazilla { get; set; }
        public string Remarks { get; set; }
        public bool Complain { get; set; }
    
        public virtual ICollection<CustomerSearch> CustomerSearches { get; set; }
    }
}
