//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsSupplierInfo
    {
        public DetailsSupplierInfo()
        {
            this.OrganizationSectorRelations = new HashSet<OrganizationSectorRelation>();
            this.SupplierAddresses = new HashSet<SupplierAddress>();
            this.Varieties = new HashSet<Variety>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SupplierCategoryId { get; set; }
    
        public virtual SupplierCategory SupplierCategory { get; set; }
        public virtual ICollection<OrganizationSectorRelation> OrganizationSectorRelations { get; set; }
        public virtual ICollection<SupplierAddress> SupplierAddresses { get; set; }
        public virtual ICollection<Variety> Varieties { get; set; }
    }
}
