//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilizer
    {
        public int Id { get; set; }
        public string Particulars { get; set; }
        public string TotalAmount { get; set; }
        public string Fertilizer1 { get; set; }
        public string Fertilizer2 { get; set; }
        public string Fertilizer3 { get; set; }
        public string Fertilizer4 { get; set; }
        public string Fertilizer5 { get; set; }
        public string Precaution { get; set; }
        public string Remarks { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
