//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.AgriculturalCulturalOperations = new HashSet<AgriculturalCulturalOperation>();
            this.BirdAndLivestockCulturalOperations = new HashSet<BirdAndLivestockCulturalOperation>();
            this.BirdAndLiveStockVaccinations = new HashSet<BirdAndLiveStockVaccination>();
            this.DiseaseAndPestManagements = new HashSet<DiseaseAndPestManagement>();
            this.EquipmentAndTechnologies = new HashSet<EquipmentAndTechnology>();
            this.Fertilizers = new HashSet<Fertilizer>();
            this.FishCulturalOperations = new HashSet<FishCulturalOperation>();
            this.HarvestingManagements = new HashSet<HarvestingManagement>();
            this.LivestockFeedPreservations = new HashSet<LivestockFeedPreservation>();
            this.NutritionalStatus = new HashSet<NutritionalStatu>();
            this.Plantings = new HashSet<Planting>();
            this.PreparationOfFeeds = new HashSet<PreparationOfFeed>();
            this.SeedProductions = new HashSet<SeedProduction>();
            this.Tips = new HashSet<Tip>();
            this.Varieties = new HashSet<Variety>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<AgriculturalCulturalOperation> AgriculturalCulturalOperations { get; set; }
        public virtual ICollection<BirdAndLivestockCulturalOperation> BirdAndLivestockCulturalOperations { get; set; }
        public virtual ICollection<BirdAndLiveStockVaccination> BirdAndLiveStockVaccinations { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<DiseaseAndPestManagement> DiseaseAndPestManagements { get; set; }
        public virtual ICollection<EquipmentAndTechnology> EquipmentAndTechnologies { get; set; }
        public virtual ICollection<Fertilizer> Fertilizers { get; set; }
        public virtual ICollection<FishCulturalOperation> FishCulturalOperations { get; set; }
        public virtual ICollection<HarvestingManagement> HarvestingManagements { get; set; }
        public virtual ICollection<LivestockFeedPreservation> LivestockFeedPreservations { get; set; }
        public virtual ICollection<NutritionalStatu> NutritionalStatus { get; set; }
        public virtual ICollection<Planting> Plantings { get; set; }
        public virtual ICollection<PreparationOfFeed> PreparationOfFeeds { get; set; }
        public virtual ICollection<SeedProduction> SeedProductions { get; set; }
        public virtual ICollection<Tip> Tips { get; set; }
        public virtual ICollection<Variety> Varieties { get; set; }
    }
}
