//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationSectorRelation
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int SectorId { get; set; }
    
        public virtual DetailsSupplierInfo DetailsSupplierInfo { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
