//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparationOfFeed
    {
        public int Id { get; set; }
        public string FeedName { get; set; }
        public string Ingredient { get; set; }
        public string Amount { get; set; }
        public string Process { get; set; }
        public string Precaution { get; set; }
        public string FeedClass { get; set; }
        public string TypesOfFeed { get; set; }
        public string Remarks { get; set; }
        public int ItemId { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
