//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Categories = new HashSet<Category>();
            this.OrganizationSectorRelations = new HashSet<OrganizationSectorRelation>();
            this.SupplierCategories = new HashSet<SupplierCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<OrganizationSectorRelation> OrganizationSectorRelations { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
    }
}
