//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCategory
    {
        public SupplierCategory()
        {
            this.DetailsSupplierInfoes = new HashSet<DetailsSupplierInfo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SectorId { get; set; }
    
        public virtual ICollection<DetailsSupplierInfo> DetailsSupplierInfoes { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
