//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAddress
    {
        public SupplierAddress()
        {
            this.DiseaseAndPestManagements = new HashSet<DiseaseAndPestManagement>();
        }
    
        public int Id { get; set; }
        public int DetailsSupplierId { get; set; }
        public int DistrictId { get; set; }
        public int UpozillaId { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
        public string WebAddress { get; set; }
    
        public virtual CustomerDistrict CustomerDistrict { get; set; }
        public virtual CustomerUpozilla CustomerUpozilla { get; set; }
        public virtual DetailsSupplierInfo DetailsSupplierInfo { get; set; }
        public virtual ICollection<DiseaseAndPestManagement> DiseaseAndPestManagements { get; set; }
    }
}
