//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIID.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variety
    {
        public int Id { get; set; }
        public string VarietyName { get; set; }
        public string Kharip1 { get; set; }
        public string Kharip2 { get; set; }
        public string RobiIndustrious { get; set; }
        public string AlltheYear { get; set; }
        public int DetailsSupplierId { get; set; }
        public string Remarks { get; set; }
        public int ItemId { get; set; }
    
        public virtual DetailsSupplierInfo DetailsSupplierInfo { get; set; }
        public virtual Item Item { get; set; }
    }
}
